### ISSUE TITLE
Backend

### ISSUE THREAD

**Issue by Rudavin** [nullworks/accgen-web#10]
Where is the backend for all of this?

**Comment by BenCat07** [comment]
Sorry the account generation backend will be kept closed source for now,
even if you did have it it wouldn't help you as valve keeps banning our
email domains

**Comment by Rudavin** [comment]
Whats the point of the frontend with no backend?

**Comment by TotallyNotElite** [comment]
> Whats the point of the frontend with no backend?
@Rudavin the account generator can be accessed at accgen.cathook.club

**Comment by Rudavin** [comment]
Im aware, but I was interested in the backend as well, seeing as I wanted to implement it into my own website (while giving full credit ofc)

**Comment by BenCat07** [comment]
Well you can only access our database as of right now, generating your own accs os basically impossible due to the amount of maintenance needed

**Comment by TotallyNotElite** [comment]
@Rudavin Yea sorry, the backend is currently not ready for an open source release (we might start working on it sooner or later) and the actual generator will be kept closed for the foreseeable future.

**Comment by Rudavin** [comment]
Okay, sounds good. Thankyou for clearing that up for me.
