### ISSUE TITLE
Gmail Forwarding

### ISSUE THREAD

**Issue by SlovakianGuyy** [nullworks/accgen-web#100]
Hi, i created Gmail forwarding to create Account but problem is that i reloading website and mail still isn't confirmed. Can someone help ? http://prntscr.com/o6yvqd

**Comment by Ashesh3** [comment]
Make sure your Google account/Gmail language settings is English. Then try agin after removing that email.

**Comment by SlovakianGuyy** [comment]
Oh, works now.. Thanks :D
