### ISSUE TITLE
Src not working

### ISSUE THREAD

**Issue by skrrtcc** [nullworks/accgen-web#11]
The source is not working 
using Apache btw

**Comment by BenCat07** [comment]
more informatio needed

**Comment by BenCat07** [comment]
doesn't work basically tells us: 
Yes

**Comment by martsklav** [comment]
Hello! The source is just for the frontend, so self hosting wouldn't give you any significant benefit. The most likely culprit for why it doesn't work is our use of recaptcha, this essentially means you can't self host since the backend, which handles that stuff, is not OS as of yet (or ever most likely).
- Kisak (backend dev)

**Comment by skrrtcc** [comment]
https://gfycat.com/IlliterateGiganticGalah

**Comment by skrrtcc** [comment]
My java scripts is working, Im aware this is a front end

**Comment by martsklav** [comment]
Have you changed the sitekey to one with localhost as one of the allowed urls? 
- Kisak (backend dev)

**Comment by skrrtcc** [comment]
There was no instructions to go with this.....

**Comment by martsklav** [comment]
The source wasn't primarily intended for self-hosting, but I get what you mean.
For the captcha to work, you need to have already set up backend integration for recaptcha v2 invisible, for which you can find documentation here: https://developers.google.com/recaptcha/docs/invisible
After making a new captcha at https://www.google.com/recaptcha, you will have 2 keys, one of which you will use for the backend and one for the frontend in the form of this string: https://github.com/nullworks/accgen-web/blob/28f87d21daeeb5cfb58f11784786a81b1d11124b/static/js/index.js#L14
How you implement it is generally up to you, but the gist of it is that the backend needs to accept a get request from the frontend with it being essentially site.com/account/captchasolution, which should respond with an 
```{ error: String, code: int }```
 object in case of an error and a 
```{ login: String, password: String, email: String, steamID: String } ``` 
object in case of success.

**Comment by skrrtcc** [comment]
thanks ill try this in a bit

**Comment by Ashesh3** [comment]
> I tried to implement it will the following instructions
> https://sascodes.com/gen.html
> I have uploaded my html if you can point out whats wrong or broken that would be great
> [website.zip](https://github.com/nullworks/accgen-web/files/2929052/website.zip)
> ![image](https://user-images.githubusercontent.com/38410101/53777128-1be88b80-3ead-11e9-98ce-83d37239aa50.png)
> Btw

You should use "v2 Invisible" and not "v2 Checkbox", update your sitekey in index.js again with the invis recaptcha key.

-DedSec

**Comment by skrrtcc** [comment]
Give me 8 hours and I'll test it again

**Comment by skrrtcc** [comment]
It's not working still :|

**Comment by BenCat07** [comment]
In what way

**Comment by Ashesh3** [comment]
Self hosting will not work because our accounts database server only sends accounts to http://accgen.cathook.club due to server sided recaptcha verification.

You'll probably end up setting a non functional website.

**Comment by martsklav** [comment]
> It's not working still :|

Does updating the frontend work? Google have recently moved some of their recaptcha v2 resources to another location, we have since made changes to fix this, but it means you will have to update for the frontend to work too.

- Kisak (backend dev)
