### ISSUE TITLE
I forgot my password and the email is not accessible.

### ISSUE THREAD

**Issue by AdonisLMAO** [nullworks/accgen-web#12]
the email is nosyuncoveredpony@accgenemails.ignorelist.com and i dont have access to it.

i need it back as it has my CS acc with my csgo LEM wingman rank,

please help.

**Comment by AdonisLMAO** [comment]
EXTRA: On the generator it says the email is inboxkitten. but its not. I cant access it in any way.

Help please.

**Comment by AdonisLMAO** [comment]
Also i didnt change the password. Please help me.

**Comment by AdonisLMAO** [comment]
Also i didnt change the password. Please help me.

**Comment by BenCat07** [comment]
nosyuncoveredpony@accgenemails.ignorelist.com should redirect to nosyuncoveredpony@inboxkitten.com

**Comment by AdonisLMAO** [comment]
Nothing arrives when i reset password. Any known reason why?

**Comment by BenCat07** [comment]
@TotallyNotElite please fix

**Comment by TotallyNotElite** [comment]
@AdonisLMAO please give me an email I can contact you with. I can pull the password from our database for you.

**Comment by AdonisLMAO** [comment]
mikocsofficial@gmail.com

Jurriaanvanbentum@gmail.com

Screentopperroblox@gmail.com

all work

**Comment by Ashesh3** [comment]
@AdonisLMAO We got your email and will get back soon

**Comment by AdonisLMAO** [comment]
Thanks a lot :D

**Comment by BenCat07** [comment]
Np i guess

**Comment by AdonisLMAO** [comment]
i havent gotten the account yet btw

**Comment by BenCat07** [comment]
Uh

**Comment by BenCat07** [comment]
Sorry, something went wrong and noone actually saves your email, can you resend it please, thanks

**Comment by AdonisLMAO** [comment]
mikocsofficial@gmail.com

jurriaanvanbentum@gmail.com

screentopperroblox@gmail.com

any one of these will work

**Comment by BenCat07** [comment]
Sent you a mail

**Comment by BenCat07** [comment]
Close this issue once confirmed

**Comment by Ashesh3** [comment]
No further password resets requests are being entertained.
