### ISSUE TITLE
Generated Account comes with different mail Help!

### ISSUE THREAD

**Issue by ifeyatta** [nullworks/accgen-web#13]
Generated Account comes with Different mail!
@europe.hmail.us is what steam says the mail is.
@inboxkitten.com is what generator said mail was.
I tried to change password and mail but confirmation mail doesn't come to @inboxkitten.com

Help Please!

**Comment by BenCat07** [comment]
Well actually the email is not accessible rn, if you want your Account login and password then send a mail to BenCat07@gmail.com with it's email, thanks

**Comment by ifeyatta** [comment]
No i wanted to access the mail (@europe.hmail.us) to retrieve code needed for changing mail and password on steam.

**Comment by BenCat07** [comment]
No wait, my bad

**Comment by ifeyatta** [comment]
So the mail ending with @europe.hmail.us was used to create the account ?

**Comment by BenCat07** [comment]
Yeah, we had a way to redirect mail to inboxkitten.com so we provided that instead since thet mail cannot be directly accessed

**Comment by BenCat07** [comment]
May need to message steam support
