### ISSUE TITLE
email is not accessible

### ISSUE THREAD

**Issue by d3xyy** [nullworks/accgen-web#15]
I trying to recover password on steam, when i create account my email is on inboxkitten, but after 1 day, is new email now:
b**************@a***********.c**
i think is @accgenemails.com, my login is broadfirsttrout. Send me new email please, i dont see recover mail on inboxkitten.

**Comment by BenCat07** [comment]
Yeah sorry the email is not accessible, if you want to recover your password send your account name to my email BenCat07@gmail.com i will recover it.

**Comment by Ashesh3** [comment]
Hello.

We cannot verify if the account in question belongs to you, hence for security reasons we are unable to grant you a password recovery. Thanks for understanding.

Regards

**Comment by d3xyy** [comment]
> Hello.
> 
> We cannot verify if the account in question belongs to you, hence for security reasons we are unable to grant you a password recovery. Thanks for understanding.
> 
> Regards

I can show you my steam files, i playing with this account. I can send you all informations about this account, matches played etc.

**Comment by d3xyy** [comment]
Add me Discord: dexy#4360

**Comment by Ashesh3** [comment]
Please note that no password recovery request s will be entertained after this final recovery.

**Comment by Ashesh3** [comment]
No response from the user on discord, closing.
