### ISSUE TITLE
Same email being used for most of the generated alts?

### ISSUE THREAD

**Issue by AdovinOFFICIAL** [nullworks/accgen-web#18]
Occasionally when I generate an alt from the site the email for it is always "not_user_accessible_sorry" most of the time. **not_user_accessible_sorry@inboxkitten.com**

**Comment by BenCat07** [comment]
No email is just not accessible.

**Comment by AdovinOFFICIAL** [comment]
Yeah but I'm saying that the alts that I get from the site keep using that same email

**Comment by Ashesh3** [comment]
The actual email used can be found in your account settings, the email shown on our website just says it's not accessable by public, go to your steam account settings and see the real email if you wish to.
