### ISSUE TITLE
Lost my password and mail

### ISSUE THREAD

**Issue by kuqwi1** [nullworks/accgen-web#19]
I lost my password and email of account with some cloud saves, so i need to return it but i cant log in cuz i didnt saved my password, and cant reset password cuz i didnt save my email either, so all i got is a login of this acc: redundantsimplisticguanaco. Can i watch my history of created accounts or can you find password in your data base and tell me?

**Comment by TotallyNotElite** [comment]
I'll discuss this with the rest of the team tomorrow. I'll get back to you.

**Comment by TotallyNotElite** [comment]
Hello! I've discussed this with the rest of the team, and we have decided against recovering passwords for our users for the following reasons:

- A malicious actor could request passwords for accounts he doesn't own.
- It's the users own responsibility to take care of their account credentials.

In the future we might store generated accounts in the browsers cookies to prevent accounts loss.
