### ISSUE TITLE
Api key

### ISSUE THREAD

**Issue by CzroP** [nullworks/accgen-web#21]
Where should i replace the api key that given.

**Comment by Ashesh3** [comment]
What do you mean? You want an api key or you wanna know how to use the key?

**Comment by CzroP** [comment]
Wanted to know how to use the API key for web hosting because i gone through the code just a HTML.
Where should i put the API key to get the account generated?

**Comment by BenCat07** [comment]
use the api url you also get given it gives you one acc, rest you have to code
