### ISSUE TITLE
 API KEY? CAN USE IN OTHER LANGUAGES

### ISSUE THREAD

**Issue by VirtusHostiz** [nullworks/accgen-web#22]
Hello, I would like to know how to apply the Cathok API to non-Web services, such as Node.JS or Python, Java, and so other services without having connection with HTML, php etc

**Comment by BenCat07** [comment]
In node.js: use request and download the api url link

**Comment by VirtusHostiz** [comment]
Help for code???
Node JS , (Discord)

**Comment by Ashesh3** [comment]
> Help for code???
> Node JS , (Discord)


```
const request = require('request');
request('https://catbot.club:2053/api/v1/account/API_KEY_HERE', function (error, response, body) {
    if(error)
         console.log('error:', error); // Print the error if one occurred
  console.log('body:', body); // Print account details
});
```
