### ISSUE TITLE
I changed the key reCaptcha and anyway it keeps giving error ...

### ISSUE THREAD

**Issue by whitegf** [nullworks/accgen-web#23]
I changed the key reCaptcha and anyway it keeps giving error ...

**Comment by whitegf** [comment]
![image](https://user-images.githubusercontent.com/44205014/54879977-86db1180-4e1e-11e9-91aa-f764219b2cdc.png)

**Comment by TotallyNotElite** [comment]
Yes. You cannot simply change the recaptcha key and expect it to work.

**Comment by whitegf** [comment]
What else do I have to change?

**Comment by Ashesh3** [comment]
@whitegf you need a server which validates the keys and gives accounts, do you have a hosting server?

**Comment by whitegf** [comment]
@Ashesh3  yes i have

**Comment by Ashesh3** [comment]
> @Ashesh3 yes i have

Have you updated the secret key on your server? and changed site key on the client site website?

**Comment by whitegf** [comment]
@Ashesh3 
yes ... could you make a quick step by step quotation of what are the processes for me to see if I'm not forgetting something?

**Comment by BenCat07** [comment]
Just FYI if you host the frontend you also need to set up your own backend which we cannot supply
