### ISSUE TITLE
API KEY

### ISSUE THREAD

**Issue by ClumsyYT** [nullworks/accgen-web#24]
Can i get an api key please i dont have telegram

**Comment by Ashesh3** [comment]
Tell us why would you need an API key.

**Comment by ClumsyYT** [comment]
I would like to have an api key to put this on my site because i think it would be cool to have on my site and i would like to see if i can make a discord bot that would work with the api key

**Comment by Ashesh3** [comment]
> I would like to have an api key to put this on my site because i think it would be cool to have on my site and i would like to see if i can make a discord bot that would work with the api key

Tell us your discord and we will pm you the key

**Comment by BenCat07** [comment]
didn't respond. closed.
