### ISSUE TITLE
API KEY

### ISSUE THREAD

**Issue by FossilOG** [nullworks/accgen-web#25]
Could I have an API Key?

Reason: I want an API Key because I am making a Steam Generator Discord Server! and making a Discord Bot that when you do !account You get a message that sends you a Steam Account! But they have to click on the verify reaction to make sure they follow the rules I will be adding a 20 seconds or 1 minute cooldown on the command!

Discord: Fossil
#3643

**Comment by TotallyNotElite** [comment]
Hello. We do not hand out API keys using the GitHub issue tracker. Please send /request (your reason) to @sag_stats_bot on telegram.
