### ISSUE TITLE
API Key @sag_stats_bot

### ISSUE THREAD

**Issue by VTRSpeedMan** [nullworks/accgen-web#26]
Am I required to complete the captcha? because I need to make a macro to obiter the accounts automatically .... or how long in how long can I generate an account without filling the capcha?
@sag_stats_bot

**Comment by BenCat07** [comment]
API Key == no captcha

**Comment by BenCat07** [comment]
You just have to use the API Key link you get

**Comment by VTRSpeedMan** [comment]
onde consigo uma Key?

**Comment by BenCat07** [comment]
Please speak english i don't understand a word

**Comment by VTRSpeedMan** [comment]
Where can I get a Key?

**Comment by BenCat07** [comment]
t.me/sag_stats_bot, use /request {Insert YOUR Reason} to request a key
