### ISSUE TITLE
aPI kEY

### ISSUE THREAD

**Issue by Casper1337235** [nullworks/accgen-web#27]
/request [i want many account so i can give me commend bot on csgo pls give me key mens.]

**Comment by Casper1337235** [comment]
/request [i want many account so i can give me commend bot on csgo pls give me key mens.]

**Comment by TotallyNotElite** [comment]
Hello. We do not hand out API keys using the GitHub issue tracker. Please send /request (your reason) to @sag_stats_bot on telegram.
