### ISSUE TITLE
Api Key

### ISSUE THREAD

**Issue by DonJTru** [nullworks/accgen-web#28]
/request Me and my friends are trying to make a website that will allow people to create accounts for different things (Steam Spotify Minecraft, etc) and the telegram link I was given doesn't work for me. and you can also get accounts in bulk for cheap (IE 100 accounts for $0.99 usd)

edit: my discord is        I am Pan(sexual)#5700

**Comment by Ashesh3** [comment]
>  telegram link I was given doesn't work for me
Please tell us how is it not working.

**Comment by DonJTru** [comment]
> > telegram link I was given doesn't work for me
> 
> Please tell us how is it not working.

when ever I click the button it does nothing, no new page or anything. The link on the website directly (has https://tele.click/sag_stats_bot) isn't in English, and the other link I was given (forgot it now) doesn't work when I click it.

**Comment by Ashesh3** [comment]
> > > telegram link I was given doesn't work for me
> > 
> > 
> > Please tell us how is it not working.
> 
> when ever I click the button it does nothing, no new page or anything. The link on the website directly (has https://tele.click/sag_stats_bot) isn't in English, and the other link I was given (forgot it now) doesn't work when I click it.

Try https://t.me/sag_bot

**Comment by TotallyNotElite** [comment]
Stale
