### ISSUE TITLE
Account count broken and "Generate Many" button also broken

### ISSUE THREAD

**Issue by AdovinOFFICIAL** [nullworks/accgen-web#29]
Account count is -13743309 (in the negative values) might be a visual bug since it seems to give me accounts just fine regardless. Although the "Generate Many" button generates two accounts, but they are the same account.
![chrome_2019-04-01_21-20-39](https://user-images.githubusercontent.com/44043300/55371545-3588ed00-54c4-11e9-8e91-ac78a38ec7ed.png)

**Comment by Ashesh3** [comment]
https://i.imgur.com/pjraE9Q.jpg
