### ISSUE TITLE
Use reCAPTCHA with recaptcha.net

### ISSUE THREAD

**Issue by wordlesswind** [nullworks/accgen-web#34]
recaptcha.net contains all the servers owned by Google (including China Shanghai server)

and www.google.com/recaptcha haven't China Shanghai server.

**Comment by BenCat07** [comment]
Well this says something else:
![image](https://user-images.githubusercontent.com/13179138/56439724-73b94580-62e7-11e9-9ad1-9e6be106621c.png)

but i did it anyways

**Comment by wordlesswind** [comment]
Maybe you can test on here: [https://en.greatfire.org/https/www.recaptcha.net](https://en.greatfire.org/https/www.recaptcha.net)
![screencapture-en-greatfire-org-https-www-recaptcha-net-2019-04-20-03_20_57](https://user-images.githubusercontent.com/9050713/56440207-5900c400-631b-11e9-9e3f-37b796fd5b25.png)

And thank you xD

**Comment by TotallyNotElite** [comment]
Hello. We switched to recaptcha.net. Please let us know if it works!

**Comment by wordlesswind** [comment]
It is working for me, thank you!
