### ISSUE TITLE
Help, how can I access the mail?

### ISSUE THREAD

**Issue by JuanJose15** [nullworks/accgen-web#38]
I would like to access the email to change it. is this ninemomentousparrot@inboxkitten.com I hope you can solve this. I have the full account, the password, the username and the email in a notebook, but I can not access it. I do not know how to access the mail. Thank you very much for your attention

PS: if you want a test, I'll gladly give it to you. Thank you

**Comment by BenCat07** [comment]
you can find the inbox kitten one on inboxkitten.com.

**Comment by JuanJose15** [comment]
I'm sorry, I have another problem. I do not receive anything in that email, but when I see the Steam email it is another: ninemomentousparrot@accgenemails.ignorelist.com. How do I access that email? Thank you

**Comment by JuanJose15** [comment]
I'm sorry, I have another problem. I do not receive anything in that email, but when I see the Steam email it is another: ninemomentousparrot@accgenemails.ignorelist.com. How do I access that email? Thank you

**Comment by BenCat07** [comment]
That domain no longer exists, sorry you cannot receive any mail

**Comment by JuanJose15** [comment]
oh ok thanks for your attention
