### ISSUE TITLE
removing accounts from history

### ISSUE THREAD

**Issue by ultramemer** [nullworks/accgen-web#39]
that would be great in situations like (especially when you have lots of accounts in your history) :
you generated 10 accounts, in 4 of which you ragehacked in csgo/tf2
they got banned, you dont need these accounts and you obviously wont log on these accounts anymore
to not clog up your accounts history you just remove these banned accounts

**Comment by xsilent007** [comment]
You can clear your browser cookies on the site for now I guess... @ultramemer

**Comment by gznster** [comment]
yes this is needed.

**Comment by Ashesh3** [comment]
Clear localstorage, for now. Planned.
