### ISSUE TITLE
Просрал аккаунт

### ISSUE THREAD

**Issue by YaTeupe** [nullworks/accgen-web#40]
Я просрал аккаунт.В генераторе Сделал аккаунт потом после 10 аккаунтов или удаления кеша не помню просрал аккаунт.

**Comment by BenCat07** [comment]
Sorry could you repeat that in english?

**Comment by Vikquick** [comment]
> Sorry could you repeat that in english?

Don`t pay attention to his issue, he just lost one of his generated accounts cause of his inadvertency

**Comment by BenCat07** [comment]
Hm well i cannot aid with recovery unless he has actual proof he owns it anyways
