### ISSUE TITLE
AccGeneratorSteam

### ISSUE THREAD

**Issue by plainpineapplebg** [nullworks/accgen-web#41]
I can't login in an account from the generator
I made it Steam Guard Protected and now i can't connect to this account...
I invested money in it.....
Any suggestions? + I asked in steam support, nothing they can do.

**Comment by ExactAkatsuki** [comment]
> Any suggestions?

Not invest money into a generated account...

**Comment by Ashesh3** [comment]
> I can't login in an account from the generator
> I made it Steam Guard Protected and now i can't connect to this account...
> I invested money in it.....
> Any suggestions? + I asked in steam support, nothing they can do.

If you generated it using our service, tell us the username here and we might be able to help you out.
