### ISSUE TITLE
API / Official Discord Bot

### ISSUE THREAD

**Issue by Zordem** [nullworks/accgen-web#42]
Hello SAG Team,
I made an discord bot with your API and only gave it to 5 servers due the rate limit of 500.
 
Later i saw you made an official bot (someone said me) and i wanted to ask if its possible to make a partnership that i care about the bot and anything around the bot:
- profile on discord bot sites
- stats (how many accs get generated with the bot
- commands
- support
- hosting
- advertising

If thats not what your like to have i would like to apply as discord bot developer 

you can contact me over discord:
zordem#2630
if you have questions

Have a nice day
Greetings zordem

**Comment by BenCat07** [comment]
No we made no offical discord bot.

**Comment by Zordem** [comment]
SOmeone said to me hes hosting an official SAg Steam acc bot

**Comment by Zordem** [comment]
http://prntscr.com/nn4i78

**Comment by Zordem** [comment]
When you dont have an official till yet.
Why not make one its cool to have it on discord...

**Comment by Zordem** [comment]
I would do it but need an unlimted API key to make it for everyone
Discord LINK (my bot): https://discord.gg/rMES5v

If you say okey make one i would make an patron command and ad for the patron in the bot link original site etc

**Comment by BenCat07** [comment]
1. We still don't have and want one, if someone makes a bot sure, they can make one, but there is no Offical one.
2. Unlimited API keys should be in the hand of **noone** not even any of our devs have one.

**Comment by Zordem** [comment]
okey
