### ISSUE TITLE
API got banned

### ISSUE THREAD

**Issue by wege2003** [nullworks/accgen-web#43]
{"error":"API services have been suspended temporarily, please wait for further updates."}

Please unban my api i need it for my steam services please unban

**Comment by BenCat07** [comment]
I can't unban starting at the fact that i have no idea which key... just send your Telegram username

**Comment by wege2003** [comment]
on telegram Clemi361

**Comment by BenCat07** [comment]
Sorry but due to frequent abuse regarding Report Bots we will not be unlocking your API Key, if the report bot works you only need 13 accounts.

**Comment by wege2003** [comment]
but i dont need it for report bot any more i need it for my other steam services please
