### ISSUE TITLE
Email Domain Banned

### ISSUE THREAD

**Issue by borduser** [nullworks/accgen-web#45]
Hey dude, I'm having a problem to generate a new account with your generator. 
After inserting Catptcha the following message appears:

An error has occured:
Email Domain banned.. Please wait for us to update it

Can you help me to solve that?

**Comment by existance-is-futile** [comment]
okay a domain is the end of the email (like @gmail.com @yahoo.com etc.) meaning the custom domain they used was banned by steam for bieng a well account generator  maybe it was associated with cheaters with the amount of accounts banned because you can report a cheater or a cheat to valve so someone probably caught on to it while raging at someone cheating so they reported the profile and found and reported the generator

**Comment by existance-is-futile** [comment]
does that help solve your question?

**Comment by existance-is-futile** [comment]
also you can't do anything about the error the dev team has to create a new domain

**Comment by borduser** [comment]
In fact this did not help me with reporting the problem. I understand that the email domain is banned, and this is due to many causes, but the point is that the platform service (https://accgen.cathook.club) is inactive because of this, apparently not only for me but for all users, I tested using proxy in the browser and VNP to see if it was anything related to my route.

**Comment by borduser** [comment]
I am reporting here to call the development team's attention to whether they will provide a solution to this.

**Comment by existance-is-futile** [comment]
oh aight

**Comment by borduser** [comment]
Thank you for trying to help.

**Comment by existance-is-futile** [comment]
as an alternative while you wait you can just make another gmail account and make a new account manually because (in my experience at least) when you get vac banned you can still sign up for a new account with the same email.

**Comment by BenCat07** [comment]
1. This issue was resolved
2. Steam all banned the free top level domains
3. This is NOT a vac but email domain ban
4. Gmail and yandex will not work for this due to their unreliability and forcing us to make everyone share one email

**Comment by borduser** [comment]
Thanks bro!
