### ISSUE TITLE
API Banned

### ISSUE THREAD

**Issue by wege2003** [nullworks/accgen-web#46]
{"error":"API services have been suspended temporarily, please wait for further updates."}

Please unban my api i need it for my steam services please unban
on telegram Clemi361
but i dont need it for report bot any more i need it for my other steam services please

**Comment by pxoss** [comment]
Are you joking? Joining the Telegram announcements will tell you that all API are suspended because Steam added reCaptcha to registration.

**Comment by BenCat07** [comment]
Look, i can give you your api key back if you provide a good reason, "for my other steam services" is **not** of of those reasons

**Comment by wege2003** [comment]
ok i need it because of my discord bot it gives others on my discord steam accounts fast and quickly please unlock it again
