### ISSUE TITLE
API services have been suspended temporarily

### ISSUE THREAD

**Issue by ExactAkatsuki** [nullworks/accgen-web#49]
Haven't been able to use the API for a while now (maybe 2 weeks?). I understand "temporarily" though I don't remember exactly how long, I've been getting this error long enough to warrant me asking.

**Comment by codsecbr** [comment]
me too

**Comment by VirtusHostiz** [comment]
me too ;(

**Comment by Ashesh3** [comment]
API services have been suspended for now.
