### ISSUE TITLE
being a patreon. 

### ISSUE THREAD

**Issue by gznster** [nullworks/accgen-web#51]
I bought patreon but no access to the website.
https://i.imgur.com/1np9YyY.jpg

**Comment by BenCat07** [comment]
Could i know your patreon id + name and possibly your profile link? We will whitelist you incase patreon failed.

**Comment by gznster** [comment]
https://www.patreon.com/user/creators?u=20553069
20553069
the telegram link is broken and i can't access the custom generator.

**Comment by BenCat07** [comment]
We are currently whitelisting you, sorry for the trouble

**Comment by gznster** [comment]
Thanks this is solved, just a question whether custom generator requires me to solve the capcha sometimes?

**Comment by BenCat07** [comment]
@gznster Yes it does
