### ISSUE TITLE
Patreon

### ISSUE THREAD

**Issue by Kurisez** [nullworks/accgen-web#53]
Hi, I'm a patreon and I cannot use the custom account maker.

It always tells me this.

An Unknown Error has occured!
There was a problem while checking your patron status.
    
An error has occured:
You need to be a Patron to access this feature!

Here's my patreon account: https://www.patreon.com/user/creators?u=20000954

**Comment by Kurisez** [comment]
![Capture](https://user-images.githubusercontent.com/51097312/58438682-0777f180-809e-11e9-9084-7831e5bdd85d.PNG)

**Comment by Kurisez** [comment]
Any help is appreciated.

**Comment by BenCat07** [comment]
Resolving, sorry for the Hassle

**Comment by robertplayscz** [comment]
@BenCat07 can you help me Now?

**Comment by Kurisez** [comment]
I still cannot use the custom account generator. Please help!

https://gyazo.com/fdc5f7262b778e7030d634f11d8f7440
https://gyazo.com/f31285ec8f0b74056461745b0b990d76

**Comment by Ashesh3** [comment]
Should be fixed
