### ISSUE TITLE
Live Feed: Steam Authentication Codes

### ISSUE THREAD

**Issue by darkenedcolossal** [nullworks/accgen-web#56]
I grew fond of a generated account and want to assign my own email address. But Steam wants to send an email to my "old" one with some code/link.
Would be nice if I could view them on the generator website.

Apart from this feature request: Any hints, how to achieve changing the mail address?

**Comment by fireshotz** [comment]
.

**Comment by mrpixel2** [comment]
im having the same problem and have no clue

**Comment by Ashesh3** [comment]
To change email, add a phone number, recover account using phone number then you can change the email without having access to old email.

We don't have access to emails, since we change domains so we can't provide you with codes.
