### ISSUE TITLE
Mudbox.ml

### ISSUE THREAD

**Issue by saukinho** [nullworks/accgen-web#6]
Hello, I'm writing here cause I dont know how to contact you.

Mudbox.ml is down since 2 days ago, so Steam Account generator FIX is not working anymore... :(

**Comment by saukinho** [comment]
Its working joining instead the https://tempmail.top/ link

**Comment by TotallyNotElite** [comment]
Is this issue related to accgen.cathook.club?

**Comment by BenCat07** [comment]
Working on a fix right now.

**Comment by Ashesh3** [comment]
@saukinho fixed in new release.
