### ISSUE TITLE
Accounts being deleted

### ISSUE THREAD

**Issue by iNeedSteamAccounts** [nullworks/accgen-web#60]
A bunch of my generated accounts are deleted by the steam support, when I try to log in it tells me.
Is that a problem with the accgen or generated accounts in general or my problem related to a yet unknown reason?

**Comment by x3nt1x** [comment]
Same,

My account got suspended by steam support and I can't recover it because I don't have access to email of that account.

Is there any way to contact the developer or can I do something myself about this?

**Comment by dumbasPL** [comment]
Same hare,
80+h of gameplay and acc suspended with no way to recover it.

**Comment by TotallyNotElite** [comment]
Gr8... Could I know the usernames of the accounts affected?

**Comment by Over9000Usernames** [comment]
Generated a single account and it was instantly suspended. I think Steam is angry.

**Comment by x3nt1x** [comment]
Account login name: GiantHolisticCobra

**Comment by iNeedSteamAccounts** [comment]
Acc Names?
EvenLearnedAlpaca, ThickHighpitchedPorcupine, ShakyGodlySalamander, SickCravenQuail, AbjectAjarCormorant

**Comment by QLthund3rbolt** [comment]
Happened with me too....lost 40k accounts today. IM TOTALY MAD....my friend could had free 2000 usd but accounts got fucked xD lmaoo i couldnt even use my other file....this month 20k acc all locked sheet......rip......

**Comment by TotallyNotElite** [comment]
Yep all accounts are gone.

**Comment by Over9000Usernames** [comment]
So that's why my accounts I was earning prime on got destroyed...

**Comment by x3nt1x** [comment]
> Yep all accounts are gone. They banned accounts that were used by legit users.

Wait, but I still see the profile

**Comment by Over9000Usernames** [comment]
> 
> 
> > Yep all accounts are gone. They banned accounts that were used by legit users.
> 
> Wait, but I still see the profile

Huh? You can see but can't log in?

**Comment by x3nt1x** [comment]
> > > Yep all accounts are gone. They banned accounts that were used by legit users.
> > 
> > 
> > Wait, but I still see the profile
> 
> Huh? You can see but can't log in?

I mean when I enter the URL of the profile to browser the profile still shows

**Comment by Over9000Usernames** [comment]
> 
> 
> > > > Yep all accounts are gone. They banned accounts that were used by legit users.
> > > 
> > > 
> > > Wait, but I still see the profile
> > 
> > 
> > Huh? You can see but can't log in?
> 
> I mean when I enter the URL of the profile to browser the profile still shows

Yeah. That's why they are suspended.

**Comment by FinalException** [comment]
@TotallyNotElite so the acc gen is dead?

**Comment by TotallyNotElite** [comment]
> @TotallyNotElite so the acc gen is dead?

Nope. We're working on a solution.

**Comment by Yolotalo** [comment]
OOF Steam is mad bois

**Comment by silentshotghost** [comment]
Y'all got fucked omegalul

**Comment by silentshotghost** [comment]
ig it's time to go back to my private account generator

**Comment by mytopdog** [comment]
> ig it's time to go back to my private account generator

stop flexing

**Comment by mrpixel2** [comment]
> > @TotallyNotElite so the acc gen is dead?
> 
> Nope. We're working on a solution.

any way we can get them back when u fix it?

**Comment by silentshotghost** [comment]
if they fix it no one will receive your accounts back unless you go through steam

**Comment by maxinimize** [comment]
lol if you had changed the email of the generated acc, u will be fine at this time

**Comment by TotallyNotElite** [comment]
> > > @TotallyNotElite so the acc gen is dead?
> > 
> > 
> > Nope. We're working on a solution.
> 
> any way we can get them back when u fix it?
> i had just got nova master in cs phat L

Message steam support and ask them about it.

**Comment by TotallyNotElite** [comment]
The web gen is fixed now btw.

**Comment by mrpixel2** [comment]
> > > > @TotallyNotElite so the acc gen is dead?
> > > 
> > > 
> > > Nope. We're working on a solution.
> > 
> > 
> > any way we can get them back when u fix it?
> > i had just got nova master in cs phat L
> 
> Message steam support and ask them about it.

i did before i got banned i was trying to get the email switched  and no i didnt menchion that the alt was generated

**Comment by mytopdog** [comment]
Now you have to have chrome addon?

**Comment by BenCat07** [comment]
Recap:
- Steam banned all temp emails.
- We are working on a solution, Accounts from database are gonna be discarded
- Changing emails would likely not have helped

**Comment by mrpixel2** [comment]
> Recap:
> 
> * Steam banned all temp emails.
> * We are working on a solution, Accounts from database are gonna be discarded
> * Changing emails would likely not have helped

ok i still was able to piss off about 4 steam support agents though lol

**Comment by existance-is-futile** [comment]
around what time might this be resolved?

**Comment by existance-is-futile** [comment]
oh never mind you can still generate new accounts

**Comment by TotallyNotElite** [comment]
I'm going to mark this issue as """Solved"""

**Comment by TotallyNotElite** [comment]
Quick update everyone: We added a page for getting the email address here: https://accgen.cathook.club/recovery.html
