### ISSUE TITLE
Value Banned All Accounts

### ISSUE THREAD

**Issue by silentshotghost** [nullworks/accgen-web#61]
Valued banned all accounts under the 
Hijacking or Sharing Accounts Rule
Do not use Steam accounts which you did not create.

![jqNjmpUWJKiM6MMP](https://user-images.githubusercontent.com/37387874/58724397-4dc89b80-8391-11e9-8179-0f0b9f7ba2e2.png)

**Comment by Shaxzy** [comment]
Steam banned all accounts using tempmail. I lost a lot of CSGO prime accounts, I feel you man

**Comment by TotallyNotElite** [comment]
Hello! All newly generated accounts will not have any bans. Additionally, its possible to get accounts unbanned by valve. 
![image](https://user-images.githubusercontent.com/38938720/58749385-b7c26d00-8485-11e9-86c4-434fe385ec4a.png)

**Comment by VladmanTvCz** [comment]
> Hello! All newly generated accounts will not have any bans. Additionally, its possible to get accounts unbanned by valve.
> ![image](https://user-images.githubusercontent.com/38938720/58749385-b7c26d00-8485-11e9-86c4-434fe385ec4a.png)

How i can get account back ?

**Comment by TotallyNotElite** [comment]
> How i can get account back ?

Message steam support.

**Comment by VladmanTvCz** [comment]
> > How i can get account back ?
> 
> Message steam support.

I guess I need email

**Comment by TotallyNotElite** [comment]
> > > How i can get account back ?
> > 
> > 
> > Message steam support.
> 
> I guess I need email

Can you send us your username in https://t.me/sag_bot_chat?

**Comment by VladmanTvCz** [comment]
> > > > How i can get account back ?
> > > 
> > > 
> > > Message steam support.
> > 
> > 
> > I guess I need email
> 
> Can you send us your username in https://t.me/sag_bot_chat?

Done

**Comment by silentshotghost** [comment]
@TotallyNotElite you guys still have banned steam accounts in your database btw

**Comment by TotallyNotElite** [comment]
> @TotallyNotElite you guys still have banned steam accounts in your database btw

That's correct. We're going to keep them for something... interesting maybe.

![image](https://user-images.githubusercontent.com/38938720/58760381-51962280-8537-11e9-8d94-5d73940b0ccd.png)

**Comment by silentshotghost** [comment]
@TotallyNotElite invite me to your discord silentshotghost#5770

**Comment by TotallyNotElite** [comment]
Quick update everyone: We added a page for getting the email address here: https://accgen.cathook.club/recovery.html

**Comment by QLthund3rbolt** [comment]
Soo if i would like to get 1 of my accounts back i know the email pass account how should i write to them or where? Anyone? :)

**Comment by TotallyNotElite** [comment]
> Soo if i would like to get 1 of my accounts back i know the email pass account how should i write to them or where? Anyone? :)

https://telegra.ph/Get-your-Accounts-Un-Suspended-06-03

**Comment by panterstv** [comment]
i just need to know you just have to contact steam support with steam support and tell it was prob done by mistake and username and all that? or wut.

**Comment by TotallyNotElite** [comment]
> i just need to know you just have to contact steam support with steam support and tell it was prob done by mistake and username and all that? or wut.

Follow the guide I sent. That's how @BenCat07 got his account reactivated.

**Comment by panterstv** [comment]
> Follow the guide I sent. That's how @BenCat07 got his account reactivated.

thanks

**Comment by FeetLamer** [comment]
Hi, I'm just from another country, can you please tell me how to restore the value in my country there is no mail
emailsrvs.jumpingcrab.com help please

**Comment by panterstv** [comment]
Hello,

I'd be happy to help with the suspended account. I'm just going to need some more information to make sure that we're working with the account owner.

Please logout of Steam, and create a new support ticket using the first email address associated with the Steam account in question as the ticket contact email. Also reference this ticket number in the new ticket: HT-B42W-RKGK-WVR9 

If you no longer have access to the original email address, you will need to contact the email provider to recover it.

Please note, if you are not able to perform this action we will not be able to make changes to the account. 

Steam Support,	
Georgette
I got this from steam support @TotallyNotElite and it says i should contact them with the email of the account owner but the email i got for the account does not work and i do not really know what to do
