### ISSUE TITLE
Error returned by SAG backend! Check console for details!

### ISSUE THREAD

**Issue by silentshotghost** [nullworks/accgen-web#63]
https://pastebin.com/mM4CrkZW

**Comment by Drunkology** [comment]
Same issue for me, I'd check the console if I knew what it was talking about lol.

**Comment by silentshotghost** [comment]
https://pastebin.com/WxHQrGRb

**Comment by grisshi4ew** [comment]
How to solve a problem?

**Comment by TotallyNotElite** [comment]
Hello, this issue usually occurs when our backend doesn't receive an email from steam. This might happen because your IP has been rate-limitted by steam.

**Comment by grisshi4ew** [comment]
Thanks, VPN helped solve this problem.

**Comment by silentshotghost** [comment]
Well if y'all want a VPN - https://bit.ly/2Ki5SDx﻿

**Comment by TotallyNotElite** [comment]
I think we can now mark this as solved, since we added error handling (it will show better error messages now)
