### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by silentshotghost** [nullworks/accgen-web#66]

**Comment by QLthund3rbolt** [comment]
now up they updated custom gen. but steam iframe wont show up soo cant even create acc...

**Comment by TotallyNotElite** [comment]
> now up they updated custom gen. but steam iframe wont show up soo cant even create acc...

Are you sure? It works for me.

**Comment by TotallyNotElite** [comment]
> _No description provided._

That's what happens when someone pushes an untested change to production :man_shrugging:

**Comment by QLthund3rbolt** [comment]
> for

Well it still is not showing for me somehow. Error From console Refused to display 'https://store.steampowered.com/join/' in a frame because it set 'X-Frame-Options' to 'deny'.

**Comment by QLthund3rbolt** [comment]
> > now up they updated custom gen. but steam iframe wont show up soo cant even create acc...
> 
> Are you sure? It works for me.

Well it still is not showing for me somehow. Error From console Refused to display 'https://store.steampowered.com/join/' in a frame because it set 'X-Frame-Options' to 'deny'.

**Comment by TotallyNotElite** [comment]
> > > now up they updated custom gen. but steam iframe wont show up soo cant even create acc...
> > 
> > 
> > Are you sure? It works for me.
> 
> Well it still is not showing for me somehow. Error From console Refused to display 'https://store.steampowered.com/join/' in a frame because it set 'X-Frame-Options' to 'deny'.

Seems like you don't have the addon installed? Could that be?

**Comment by silentshotghost** [comment]
They banned your emails again

**Comment by Ashesh3** [comment]
@silentshotghost What

**Comment by TotallyNotElite** [comment]
@silentshotghost this is not gud

**Comment by silentshotghost** [comment]
Ya ik

**Comment by Ashesh3** [comment]
@TotallyNotElite Seriously?

**Comment by silentshotghost** [comment]
Y’all got discord I’m tryna chat

**Comment by Ashesh3** [comment]
@silentshotghost We're on telegram if you have that

**Comment by TotallyNotElite** [comment]
Still works for me idk what you're talking about @silentshotghost

**Comment by Ashesh3** [comment]
@silentshotghost The email still works, try again once

**Comment by TotallyNotElite** [comment]
> Y’all got discord I’m tryna chat

https://t.me/sag_bot_chat

**Comment by silentshotghost** [comment]
https://media.discordapp.net/attachments/585198123840700531/585315115268702218/unknown.png

**Comment by TotallyNotElite** [comment]
@silentshotghost

**Comment by silentshotghost** [comment]
Yes

**Comment by TotallyNotElite** [comment]
> https://media.discordapp.net/attachments/585198123840700531/585315115268702218/unknown.png

![image](https://user-images.githubusercontent.com/38938720/58860243-fb96bb80-86ab-11e9-97c9-c7273175a777.png)

**Comment by Ashesh3** [comment]
@silentshotghost Try clearing cache and refresh and try again. are  you using main page? : http://accgen.cathook.club/index.html?nocache

**Comment by silentshotghost** [comment]
Ya it worked it’s cause y’all still have banned accounts in your database

**Comment by TotallyNotElite** [comment]
> Ya it worked it’s cause y’all still have banned accounts in your database

No. The accounts in our database are no longer distributed.

**Comment by silentshotghost** [comment]
Ahhh with that many accounts tbh you can reck havoc on steam if you use them properly

**Comment by TotallyNotElite** [comment]
Take a look at #60

**Comment by QLthund3rbolt** [comment]
> > > > now up they updated custom gen. but steam iframe wont show up soo cant even create acc...
> > > 
> > > 
> > > Are you sure? It works for me.
> > 
> > 
> > Well it still is not showing for me somehow. Error From console Refused to display 'https://store.steampowered.com/join/' in a frame because it set 'X-Frame-Options' to 'deny'.
> 
> Seems like you don't have the addon installed? Could that be?

i have it installed.

**Comment by QLthund3rbolt** [comment]
> > > > > now up they updated custom gen. but steam iframe wont show up soo cant even create acc...
> > > > 
> > > > 
> > > > Are you sure? It works for me.
> > > 
> > > 
> > > Well it still is not showing for me somehow. Error From console Refused to display 'https://store.steampowered.com/join/' in a frame because it set 'X-Frame-Options' to 'deny'.
> > 
> > 
> > Seems like you don't have the addon installed? Could that be?
> 
> i have it installed.

Well i reinstalled it and boom worked :D
