### ISSUE TITLE
Steam issue

### ISSUE THREAD

**Issue by xAkiraMiura** [nullworks/accgen-web#67]
I've tried to use firefox. [Captcha failed or IP banned by steam (vpn).]
I've tried to use firefox with a VPN. [Captcha failed or IP banned by steam (vpn).]

I've tried using chrome. [Steam is limitting your account creations. Try again later.]
I've tried on firefox mobile. [Steam is limitting your account creations. Try again later.]

**Comment by silentshotghost** [comment]
Use a vpn on your desktop instead of browser and if that doesn’t work try clearing cookies or using private browser that doesn’t track data

If you need a vpn here - https://bit.ly/2Ki5SDx﻿
