### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Shazyy** [nullworks/accgen-web#7]
Is there any way to contact you? Telegram, discord, anything?

**Comment by TotallyNotElite** [comment]
Off topic

**Comment by Ashesh3** [comment]
You can drop us a message here if necessary

**Comment by BenCat07** [comment]
Or you can message t.me/BenCat07 (not DedSec but one of the devs.)

**Comment by TotallyNotElite** [comment]
Answered in PM. //closed
