### ISSUE TITLE
Banned from the website for no reason.

### ISSUE THREAD

**Issue by whoware** [nullworks/accgen-web#71]
Not sure what happened, but this is the events in realtime:

Last night I found your website, I added the addon, made an account and it worked fine, and I removed the Addon because I didn't think I would need another account for a while.

Well upon changing my mind, I came back to site Today, readded the Addon, and pressed generate.

Got met with this message: "An error has occured:
Email banned (Please contact us! https://t.me/sag_bot_chat)"

What was I even banned for, removing an addon?

I must be IP banned because I tried to see if it was bugged and I tried in Incognito, but no. It's still not allowing me to generate accounts. 
So it has to be a false IP ban.

Please help?

**Comment by existance-is-futile** [comment]
no it's not you bieng banned steam banned every account using the same email domain as the generated accounts so it means the site was unable to make an account because the email domain used was banned from steam.

**Comment by existance-is-futile** [comment]
as an alternative while you wait you can just make another gmail account and make a new account manually. but if your planning to use a cheat it's fine because (in my experience at least) when you get vac banned you can still sign up for a new account with the same email.

**Comment by TotallyNotElite** [comment]
See #72
