### ISSUE TITLE
email domain banned again...

### ISSUE THREAD

**Issue by existance-is-futile** [nullworks/accgen-web#72]
yeah i got this error message today and they are really cracking down the generator like they used to do little to nothing (from what i've seen) and now they are really attacking the generator but it makes sense for me to be punished because literally all of my accounts have been used to cheat :/

![steam acc](https://user-images.githubusercontent.com/50644172/58841007-e757ad80-861c-11e9-9382-8c65ed08d505.PNG)

**Comment by Falghere** [comment]
hpn with me too

**Comment by GGuardiaNN** [comment]
yep happened to me too

**Comment by Shadeauxx** [comment]
Is there any fix to this?

**Comment by TotallyNotElite** [comment]
> Is there any fix to this?

I'm not going to say more than "valve is stupid", you can guess what that means ;)

**Comment by Shadeauxx** [comment]
> > Is there any fix to this?
> 
> I'm not going to say more than "valve is stupid", you can guess what that means ;)

alright, well i hope the servers, or whatever's down or not working, comes back soon

**Comment by TotallyNotElite** [comment]
> > > Is there any fix to this?
> > 
> > 
> > I'm not going to say more than "valve is stupid", you can guess what that means ;)
> 
> alright, well i hope the servers, or whatever's down or not working, comes back soon

Nothing is down. It's just a ""FIX"", if you can even legally call it that, by valve.

**Comment by TotallyNotElite** [comment]
Ok valve should fire the guy that's doing these "fixes" LMAO. Accgen is back online.

**Comment by dylanzachharias** [comment]
@TotallyNotElite Its down again, any advice?

**Comment by TotallyNotElite** [comment]
Automatic system for this kind of stuff already kicked in. The thing is, we are just humans and actually need sleep xd

**Comment by dylanzachharias** [comment]
@TotallyNotElite mate wdym

**Comment by TotallyNotElite** [comment]
> @TotallyNotElite mate wdym

Our automatic system already detected something was wrong. Issue is fixed now.
