### ISSUE TITLE
i tryed to enable steam guard 

### ISSUE THREAD

**Issue by jakethefirst** [nullworks/accgen-web#74]
i need help i cant get into the new account email i put pass word in and username in and it keeps saying  that its not a real account can you help?

**Comment by existance-is-futile** [comment]
¯\_(ツ)_/¯

**Comment by existance-is-futile** [comment]
¯\_(ツ)_/¯

**Comment by existance-is-futile** [comment]
¯\_(ツ)_/¯

**Comment by jakethefirst** [comment]
toxic

**Comment by Ashesh3** [comment]
So you mean you made an account but when you tried to login, it didn't work?

**Comment by IamDontHAcker** [comment]
And I have such a problem, I turned on Steam Guard and Bach flew Steam !!! I tried to find the mail and found it, but I do not know where it is registered BlaBlaBla@valve.dont.be.sexy Help !!!! I wrote Russian via Google Translate!

**Comment by litelesslive** [comment]
Why you dont create an account yourself? No need to care with this type of problems...

**Comment by Ashesh3** [comment]
We don't provide email access to the accounts you make. We don't recommend storing valuable items on the accounts.
