### ISSUE TITLE
Valve is unbanning suspended accounts!

### ISSUE THREAD

**Issue by Kacpix2000** [nullworks/accgen-web#75]
Here's a proof: 
![gaa](https://user-images.githubusercontent.com/51484046/59108277-d075cb80-893a-11e9-988d-12ae7b546fb7.png)

**Comment by Ashesh3** [comment]
@Kacpix2000 what

**Comment by BenCat07** [comment]
@Kacpix2000 Yes, they unban your account if you send uname and email, but we have 20 million accs to do it with

**Comment by BenCat07** [comment]
@Ashesh3 Yes, they unban your account if you send uname and email, but we have 20 million accs to do it with

**Comment by kattking16** [comment]
how to contact steam support ?!?! i know what to do but i cant fucking send them a message or anything i got skins on that account =(

**Comment by Ashesh3** [comment]
@kattking16 try here: telegra.ph/Get-your-Accounts-Un-Suspended-06-03

**Comment by kattking16** [comment]
i have the email right but i don't know what to do with it can someone help plz =(

**Comment by kattking16** [comment]
> @kattking16 try here: https://telegra.ph/Get-your-Accounts-Un-Suspended-06-03

i will try this thx it looks promesing

**Comment by QLthund3rbolt** [comment]
@Ashesh3 Hey, Could you recommend any good proxy service for creating accounts. To get rid of the error 101. case 101 in your code. I tried stormproxies backconnect but it dont seem to work well at all. what proxie service you used when u created accounts with old method or even new.

**Comment by Ashesh3** [comment]
@QLthund3rbolt @TotallyNotElite answer is none? vpns are banned

**Comment by Ashesh3** [comment]
> @Ashesh3 Hey, Could you recommend any good proxy service for creating accounts. To get rid of the error 101. case 101 in your code. I tried stormproxies backconnect but it dont seem to work well at all. what proxie service you used when u created accounts with old method or even new.

Many VPNs are banned, you can try buying some hq proxies and use them, but usually proxies are banned by steam so it won't be so easy but try some paid proxy rotator or hq proxies.

**Comment by panterstv** [comment]
this is what i got when i did request like everybody else.
Please submit a new help request from the email used to register the account and we'll continue to assist when that step is completed.

At this time this request will be closed. 

Steam Support	
Steve
how do i get acces to the account email or how am i suppost to contact them with the email that the account has when i cant have acces to the email account ik the email but wont help

**Comment by kattking16** [comment]
> this is what i got when i did request like everybody else.
> Please submit a new help request from the email used to register the account and we'll continue to assist when that step is completed.
> 
> At this time this request will be closed.
> 
> Steam Support
> Steve
> how do i get acces to the account email or how am i suppost to contact them with the email that the account has when i cant have acces to the email account ik the email but wont help

what did you tell them write before getting the answer?

**Comment by panterstv** [comment]
> > this is what i got when i did request like everybody else.
> > Please submit a new help request from the email used to register the account and we'll continue to assist when that step is completed.
> > At this time this request will be closed.
> > Steam Support
> > Steve
> > how do i get acces to the account email or how am i suppost to contact them with the email that the account has when i cant have acces to the email account ik the email but wont help
> 
> what did you tell them write before getting the answer?

i did answear with the same as the one thats in the top of this github

**Comment by kattking16** [comment]
> > > this is what i got when i did request like everybody else.
> > > Please submit a new help request from the email used to register the account and we'll continue to assist when that step is completed.
> > > At this time this request will be closed.
> > > Steam Support
> > > Steve
> > > how do i get acces to the account email or how am i suppost to contact them with the email that the account has when i cant have acces to the email account ik the email but wont help
> > 
> > 
> > what did you tell them write before getting the answer?
> 
> i did answear with the same as the one thats in the top of this github

try again maybe idk it worked for me first time maybe you just got a lazy steam employee that did not want to sort your problems
