### ISSUE TITLE
API Bann Unban it pls

### ISSUE THREAD

**Issue by wege2003** [nullworks/accgen-web#76]
pls can you unban my API key i need the steam accounts for discord Bot 
API KEY : KY1E7HR-78QM4WH-NRDKR7A-Z7QFV3F

**Comment by BenCat07** [comment]
we can't, steam added recpatcha and banned all of our account reserves.

**Comment by wege2003** [comment]
and can you make new reserves?

**Comment by wege2003** [comment]
but than i need captcha api key where can i get it?

**Comment by BenCat07** [comment]
as i just said, steam added recaptcha so no we cannot, besides if we pay ridicilous rates

**Comment by martsklav** [comment]
No, the reason why the API service is suspended is we cannot maintain a surplus of accounts due to valve adding recaptcha.

**Comment by wege2003** [comment]
and where can i get captcha api for your github steam account generator?
bc i want auto captcha and not hand mode captcha

**Comment by BenCat07** [comment]
you can use the inoffical api. Look at the Network tab and check what gets called in order to make an account, then pass a solved captcha key when it's eventually needed. You need to use a paid captcha solving api from somewhere on the web.

**Comment by martsklav** [comment]
This is not the github page for the standalone generator, we are simply here to provide help with the web version, but I am pretty sure that one supports http://2captcha.com.
