### ISSUE TITLE
acc gen not working

### ISSUE THREAD

**Issue by xleduuhzinlx** [nullworks/accgen-web#78]
fix that please

**Comment by martsklav** [comment]
@xleduuhzinlx Please provide more info relevant to the situation, "fix that please" isn't enough information for us to even try to know what the problem is.

**Comment by existance-is-futile** [comment]
i think his problem is the same as mine basically right now it's taking really long to generate acccounts [a reason to think it's broken] i even caught up on all the web comics i used to read and it's still generating not sure if it's broken or the wait times have extended

**Comment by xleduuhzinlx** [comment]
yes this is the problem i'm having, it's taking too long to generate accounts

**Comment by xleduuhzinlx** [comment]
but now its working thanks
