### ISSUE TITLE
acc gen might be broken

### ISSUE THREAD

**Issue by existance-is-futile** [nullworks/accgen-web#79]
basically right now it's taking really long to generate acccounts i even caught up on all the web comics i used to read and it's still saying "generating" not sure if it's broken or the wait times have extended

**Comment by martsklav** [comment]
@existance-is-futile If it doesn't generate an account at all, even after 1-2 minutes have passed, you could try opening the network tab on devtools (crtl+shift+i) and looking at the last request (response).

**Comment by martsklav** [comment]
Otherwise, it's probably normal.

**Comment by Ashesh3** [comment]
@existance-is-futile Hello! We've found the issue and working on a fix! Thanks

**Comment by kattking16** [comment]
> @existance-is-futile Hello! We've found the issue and working on a fix! Thanks

hey, can you make a similar thing but for discord accounts?

**Comment by martsklav** [comment]
@kattking16 There are no plans for it as of now, we've had the idea before, it's just most likely not going to happen.

**Comment by kattking16** [comment]
> @kattking16 There are no plans for it as of now, we've had the idea before, it's just most likely not going to happen.

its good idea I would donate ;)

**Comment by jere021099** [comment]
Hey, every time I try a new subdomain for new email adress, I got the error saying that this email can't be used because it's a temporary email. Even the default one doesn't work anymore, does anyone have a working subdomain,or knows a way to fix it?

**Comment by Ashesh3** [comment]
> Hey, every time I try a new subdomain for new email adress, I got the error saying that this email can't be used because it's a temporary email. Even the default one doesn't work anymore, does anyone have a working subdomain,or knows a way to fix it?

only paid domains work and our default domain works (for now)
