### ISSUE TITLE
Стим guard\Steam guard

### ISSUE THREAD

**Issue by Koti213** [nullworks/accgen-web#80]
Russian:Я подключил стим гуард на логин ThickAllegedLoris56 теперь немогу войти тк просить с почты код что мне делать?
English;
I connected the Steam Guard to the login. ThickAllegedLoris56 now asks for the code that is sent to the post office, what should I do?

**Comment by Ashesh3** [comment]
You need to prove you're the real owner of that account. Please contact us at t.me/sag_bot_chat (Telegram)

**Comment by Koti213** [comment]
Хорошо

**Comment by Ashesh3** [comment]
@Koti213 Хорошо = Good

**Comment by Ashesh3** [comment]
@Ashesh3 This was manually entered (see different contents)

**Comment by Ashesh3** [comment]
Fixed.
