### ISSUE TITLE
History of generate was deleted

### ISSUE THREAD

**Issue by novycz121** [nullworks/accgen-web#82]
Hello I wanted to find an account name in history, but history didn't show up,I was deleted cookie history, please help me.

**Comment by Ashesh3** [comment]
@novycz121 Enter 
localStorage.getItem("genned_account")

In browser console

**Comment by novycz121** [comment]
@Ashesh3 nothing shows

**Comment by Ashesh3** [comment]
@novycz121 You cleared your browser cache , localstorage is wiped. Your browser forgot all stored accounts.

**Comment by novycz121** [comment]
@Ashesh3 is there any way to restore all this?

**Comment by Ashesh3** [comment]
@novycz121 Sorry but the accounts are stored on your browser, there's nothing we can do now. If you used to them login to steam.. try switching to big picture mode in steam and switching accounts

**Comment by novycz121** [comment]
@Ashesh3 and when I give you accout name can you give me password?

**Comment by Ashesh3** [comment]
Sorry, we don't do that.
