### ISSUE TITLE
email address banned 

### ISSUE THREAD

**Issue by Novrb1** [nullworks/accgen-web#83]
i have screen shot 
https://gyazo.com/5aef653b8ad18c30a3da812d2e1e4e28
idk though but i pressed generate and that said

EDIT:      https://gyazo.com/d4b4ac8866d052f8d37308deff3cfb1e

EDIT:      https://gyazo.com/2aad277a701d75238843ca2659d91dca

**Comment by Flawlessdesigner** [comment]
Same Same

**Comment by SylveonBottle** [comment]
Try again today?

**Comment by Ashesh3** [comment]
Fixed.
