### ISSUE TITLE
Account lost because of Microsoft Edge

### ISSUE THREAD

**Issue by ImAPlane** [nullworks/accgen-web#84]
Hi, 
for the acc gen i used microsoft edge, because the addon wasn't working on chrome.
now i came back from holiday and i cant access that account anymore...
is there any chance to get it back?

Kind Regards,

**Comment by Ashesh3** [comment]
@ImAPlane Open console and enter this:


localStorage.getItem("genned_account")

**Comment by ImAPlane** [comment]
Wich console tho? o.o

**Comment by BenCat07** [comment]
@ImAPlane Good question, we have no idea as most of us use Linux

**Comment by Ashesh3** [comment]
@ImAPlane Browser console, Dev tools

**Comment by Ashesh3** [comment]
@ImAPlane Browser console, Dev tools ,

**Comment by ImAPlane** [comment]
i did that, nothing gets shown, and i've never deleted any cookies or anything.

**Comment by ImAPlane** [comment]
it says Null

**Comment by BenCat07** [comment]
@ImAPlane You entered the command while on our website right?

**Comment by ImAPlane** [comment]
yeah, i misstyped it lolol , got some rn, thx

**Comment by BenCat07** [comment]
By any chance, did you use http://catbot.club/index.html back then?

**Comment by Ashesh3** [comment]
@ImAPlane Awesome! Welcome!

**Comment by BenCat07** [comment]
Oh i can't read, well then, case closed!

**Comment by ImAPlane** [comment]
well... 

its suspended, what to do?

**Comment by BenCat07** [comment]
F In the chat boys


Basically, you need to contact steam support, steam support will tell you to send a request with that accounts email and you are sad because you cab't do that

**Comment by martsklav** [comment]
@BenCat07 F
