### ISSUE TITLE
Steam support

### ISSUE THREAD

**Issue by Sovag** [nullworks/accgen-web#85]
Добрый день! 

Для того, чтобы восстановить вам доступ к аккаунту, нам нужно быть уверенными, что именно вы являетесь его создателем. К сожалению, на аккаунте нет покупок, с помощью которых мы смогли бы проверить это. Поэтому нам нужно убедиться, что вы являетесь владельцем первого электронного адреса, зарегистрированного на этом аккаунте. 

Пожалуйста, выйдите из Steam, и создайте новое обращение в службу поддержки, используя первый адрес эл. почты, зарегистрированный на этом аккаунте. Также укажите номер этого обращения: HT-93PH-BKW9-DF38 в вашем следующем сообщении.

Если доступ к этой почте утерян, вам нужно будет восстановить его через поддержку почтового провайдера.

Пожалуйста учтите, что если вы не сможете это сделать, мы не сможем произвести какие-либо действия с аккаунтом. 

Best Regards,	
Sofi

**Comment by Ashesh3** [comment]
Good day!

We are unable to verify the ownership of the account, therefore can't provide you with the account recovery options. 

Best regards,
Sofi
