### ISSUE TITLE
custom generator said im not a patreon

### ISSUE THREAD

**Issue by WLTN1** [nullworks/accgen-web#91]
Hello, i buy a patreon for you, but custom generator site still say "You are not a patreon yet".
My patreon profile: https://www.patreon.com/WLTN1

Thank you and have a nice day

**Comment by SylveonBottle** [comment]
Generator takes 30 minutes _minimum_ to update your patreon info. That's just how patreon works.

Try again today?

**Comment by WLTN1** [comment]
Hello, now i getting this error "An Unknown Error has occured! There was a problem while checking your patron status."

**Comment by Ashesh3** [comment]
Hello! Is this working now? in future you can message us on the telegram group for faster response.
