### ISSUE TITLE
Can´t generate steam accounts

### ISSUE THREAD

**Issue by sddar** [nullworks/accgen-web#94]
![s](https://user-images.githubusercontent.com/52128430/59976238-ea154500-95c1-11e9-8077-e301464f96bb.JPG)
I downloaded  and activated the SAG addon but it isn´t working. This popup shows up every time.
I am using google chrome

thx for help

**Comment by Ashesh3** [comment]
Just reinstall the addon once more then force refresh the page after restarting chrome
