### ISSUE TITLE
Steam refused to connect

### ISSUE THREAD

**Issue by FluffyPlays22** [nullworks/accgen-web#97]
![image](https://user-images.githubusercontent.com/52138970/59981653-129e3e80-95c4-11e9-8747-ad4aa8b9bcde.png)
 idk whats wrong

**Comment by Ashesh3** [comment]
Do you have our addon?

**Comment by FluffyPlays22** [comment]
yes i have the addon

**Comment by FluffyPlays22** [comment]
i fixed it i just had to reinstall the addon
