### ISSUE TITLE
"Steam is limitting account creations from your IP. Try again later."

### ISSUE THREAD

**Issue by Bunnehx** [nullworks/accgen-web#99]
I keep getting that error everytime I try to generate an account, I waited a day and it's still coming up and I'm also a patreon D;

**Comment by Ashesh3** [comment]
Can you try to make an account manually on steam's website? does that work? Let us know.

**Comment by Bunnehx** [comment]
Yeah I was able to make another steam account.

**Comment by Bunnehx** [comment]
Yeah I just made one right now and it works.
https://gyazo.com/37d9fcc6a58b6bd5451a56a33ffa004e

**Comment by Bunnehx** [comment]
It's say I'm banned now??
https://gyazo.com/e5e690dea65e733dc061470323202efd

**Comment by Ashesh3** [comment]
@Bunnehx email is banned, you're not banned. This is an issue with the website, we are working on a fix.

**Comment by litelesslive** [comment]
Well same issue with IP limitation. Looks like steam added some shenanigans to make our haxing harder. Welp.... 12accs baned in 1 day is quite a lot.

**Comment by Bunnehx** [comment]
So when will it be fixed?

**Comment by m413** [comment]
I tried to generate an account and is saying that I am banned, I was banned?

**Comment by lucasvbs101** [comment]
> Eu tentei gerar uma conta e está dizendo que estou banido, fui banido?


I'm with the same problem says that I was banned email banned in case

**Comment by iury12345-sys** [comment]
eu também estou com o mesmo problema, fla que meu e-mail esta banido e eu nao posso gerar contas

**Comment by litelesslive** [comment]
@Bunnehx email is banned, you're not banned. This is an issue with the website, we are working on a fix.
--


Its NOT you banned. Its their GMAIL banned.
